networks:
    app-trainning-network:
        driver: bridge

volumes:
    app-trainning-database:
        driver: local

services:
    app:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: app-trainning-server:1.0
        container_name: app-trainning-server
        hostname: app-trainning-server
        restart: always
        ports:
            - 3001:3000
        env_file:
            - ./server/.env
        volumes:
            - ./server:/usr/src/app
        command: ["yarn", "start:dev"]
        depends_on:
            - database
        networks:
            - app-trainning-network
        deploy:
            resources:
                limits:
                    memory: 300M

    database:
        image: postgres:latest
        container_name: app-trainning-database
        hostname: app-trainning-database
        restart: always
        ports:
            - 5433:5432
        env_file:
            - ./server/.env
        volumes:
            - app-trainning-database:/var/lib/postgresql/data
        networks:
            - app-trainning-network
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: app-trainning-nginx:1.0
        hostname: app-trainning-nginx
        container_name: app-trainning-nginx
        ports:
            - 3000:3000
        depends_on:
            - app
            - database
        networks:
            - app-trainning-network
