version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: trainning-app:1.0
    container_name: trainning-app
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ['yarn', 'start:dev']
